### ISSUE TITLE
how to setup MC Monitor by using grafana

### ISSUE THREAD

**Issue by XinBow99** [itzg/mc-monitor#11]
Hi itzg, it's a perfect project! But I don't know how to setup _**mc-monitor/examples/mc-monitor-prom**_ ,I went into this directory and successfully executed **sudo docker-compose up -d** and **sudo docker-compose logs -f**, but my Grafana doesn't receive any message, this is my configuration

**docker-compose.yml** :
<img width="509" alt="截圖 2022-03-06 下午11 35 51" src="https://user-images.githubusercontent.com/36734430/156930164-982301d6-a576-4446-ae75-13c77c0d310f.png">

**prometheus.yml**:
<img width="188" alt="截圖 2022-03-06 下午11 36 21" src="https://user-images.githubusercontent.com/36734430/156930191-55200f0d-9c32-4829-a7a0-37ade69ea6c5.png">

and **docker run -it --rm itzg/mc-monitor status --host mc.hypixel.net** command is work perfect.

**Comment by XinBow99** [comment]
I solved this problem!
I fund those errors in cadvisor:
**Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory**
**Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: operation not permitted**
add _privileged: true_ and _/proc/kmsg:/dev/kmsg_ below cadvisor and volumes via insert docker-compose.yml

**Comment by XinBow99** [comment]
:(
My Mc monitor of grafana still no data, so i tried those command to check subprocess:
monitor: curl 172.18.0.4:8080/metrics, it's work fine.
mc, it's work fine.
grafana, good.
cadvisor, good.
test http://prometheus:9090 on datasources of grafana, works.

So I'm not sure what's wrong with the Mc monitor dashboard.

**Comment by XinBow99** [comment]
oh XD I solved

**Comment by itzg** [comment]
Glad to hear. Can this be closed now?

**Comment by XinBow99** [comment]
ok, thanks you.
