### ISSUE TITLE
Docker container exits after one ping

### ISSUE THREAD

**Issue by NoskcajXela** [itzg/mc-monitor#98]
I'll apologize ahead of time if this is user error, but I run the docker container, it seems to ping and reach the server and then the container exits. I assumed the container would continue to collect data.

The command I'm running is:
`docker run -it itzg/mc-monitor status-bedrock --host [my host ip] export-for-prometheus -bedrock-servers [my host ip]`

and with that I get one line of output:
`[my host ip]:19132 : version=1.21.23 online=0 max=10`

and the container exits. I have tried the -debug flag, but I get nothing different.

**Comment by itzg** [comment]
You're invocation includes two subcommands
- status-bedrock
- export-for-prometheus

What are you actually wanting to run?

**Comment by itzg** [comment]
You can only use one subcommand at a time. So, yes, run the one you're wanting.
